
export const map1Index = {
  U: {
    width: 4,
    height: 1,
    x: 4,
    y: 0,
    collision: false,
  },
  waterpool: {
    width: 3,
    height: 3,
    x: 8,
    y: 0,
    collision: true,
  },
  floor1: {
    width: 1,
    height: 1,
    x: 9,
    y: -2,
    collision: false,
  },
  floor2: {
    width: 1,
    height: 1,
    x: 10,
    y: -1,
    collision: false,
  },
  floor3: {
    width: 1,
    height: 1,
    x: 10,
    y: -2,
    collision: false,
  },
  floor4: {
    width: 1,
    height: 1,
    x: 10,
    y: -3,
    collision: false,
  },
  floor5: {
    width: 1,
    height: 1,
    x: 11,
    y: -3,
    collision: false,
  },
  floor6: {
    width: 2,
    height: 1,
    x: 12,
    y: -1,
    collision: false,
  },
  floor7: {
    width: 1,
    height: 1,
    x: 11,
    y: -2,
    collision: false,
  },
  floor8: {
    width: 2,
    height: 1,
    x: 12,
    y: -3,
    collision: false,
  },
  floor9: {
    width: 1,
    height: 1,
    x: 13,
    y: -3,
    collision: false,
  },
  floor10: {
    width: 1,
    height: 1,
    x: 13,
    y: -1,
    collision: false,
  },
  floor11: {
    width: 1,
    height: 1,
    x: 13,
    y: -2,
    collision: false,
  },
  floor12: {
    width: 1,
    height: 1,
    x: 16,
    y: -2,
    collision: false,
  },
  floor13: {
    width: 3,
    height: 3,
    x: 3,
    y: -3,
    collision: false,
  },
  floor14: {
    width: 1,
    height: 1,
    x: 5,
    y: 0,
    collision: true,
  },
  floor15: {
    width: 1,
    height: 1,
    x: 5,
    y: -1,
    collision: true,
  },
  floor16: {//long green
    width: 1,
    height: 3,
    x: 15,
    y: -1,
    collision: false,
  },
  floor17: {//long green
    width: 3,
    height: 1,
    x: 16,
    y: 0,
    collision: false,
  },
  floor18: {
    width: 2,
    height: 2,
    x: 16,
    y: -2,
    collision: false,
  },floor19: {
    width: 1,
    height: 1,
    x: 14,
    y: -2,
    collision: false,
  },floor20: {
    width: 3,
    height: 1,
    x: 3,
    y: -6,
    collision: false,
  },floor21: {
    width: 1,
    height: 3,
    x: 3,
    y: -3,
    collision: false,
  },floor22: {
    width: 1,
    height: 4,
    x: 2,
    y: -2,
    collision: false,
  },floor23: {
    width: 1,
    height: 4,
    x: 1,
    y: -2,
    collision: false,
  },floor24: {
    width: 1,
    height: 1,
    x: 3,
    y: -6,
    collision: true,
  },floor25: {
    width: 1,
    height: 1,
    x: 2,
    y: -6,
    collision: true,
  },floor26: {
    width: 1,
    height: 1,
    x: 1,
    y: -6,
    collision: true,
  },floor27: {
    width: 1,
    height: 1,
    x: 14,
    y: -1,
    collision: true,
  },floor28: {
    width: 1,
    height: 1,
    x: 16,
    y: -1,
    collision: true,
  },floor29: {
    width: 1,
    height: 1,
    x: 11,
    y: -1,
    collision: true,
  },
  water:{
    width: 1,
    height: 1,
    x: 10,
    y: -5,
    collision: true,
  },water2:{
    width: 1,
    height: 1,
    x: 15,
    y: -6,
    collision: true,
  },water3:{
    width: 1,
    height: 1,
    x: 16,
    y: -5,
    collision: true,
  },water4:{
    width: 1,
    height: 2,
    x: 11,
    y: -4,
    collision: true,
  },water5:{
    width: 1,
    height: 1,
    x: 18,
    y: -2,
    collision: true,
  },water6:{
    width: 1,
    height: 1,
    x: 17,
    y: -2,
    collision: true,
  },water7:{
    width: 1,
    height: 1,
    x: 17,
    y: -1,
    collision: true,
  },water8:{
    width: 1,
    height: 1,
    x: 18,
    y: -1,
    collision: true,
  },water9:{
    width: 1,
    height: 1,
    x: 16,
    y: -6,
    collision: true,
  },water10:{
    width: 1,
    height: 1,
    x: 11,
    y: -6,
    collision: true,
  },water11:{
    width: 1,
    height: 1,
    x: 11,
    y: -5,
    collision: true,
  },water12:{
    width: 1,
    height: 1,
    x: 14,
    y: -4,
    collision: true,
  },water13:{
    width: 1,
    height: 1,
    x: 11,
    y: -4,
    collision: true,
  },water14:{
    width: 1,
    height: 1,
    x: 16,
    y: -4,
    collision: true,
  },
  waterIsland: {
    width: 6,
    height: 3,
    x: 16,
    y: -4,
    collision: true,
  },
  rockFloor1:{
    width: 1,
    height: 4,
    x: 0,
    y: -7,
    collision: true,
  },
  rockFloor2:{
    width: 4,
    height: 1,
    x: -1,
    y: -7,
    collision: true,
  },rockFloor3:{
    width: 1,
    height: 3,
    x: -5,
    y: -8,
    collision: true,
  },rockFloor4:{
    width: 1,
    height: 1,
    x: -4,
    y: -10,
    collision: true,
  },rockFloor5:{
    width: 1,
    height: 1,
    x: -1,
    y: -10,
    collision: true,
  },rockFloor6:{
    width: 2,
    height: 1,
    x: -2,
    y: -10,
    collision: false,
  },rockFloor7:{
    width: 4,
    height: 2,
    x: -1,
    y: -8,
    collision: false,
  },rockFloor8:{
    width: 1,
    height: 2,
    x: 0,
    y: -8,
    collision: true,
  },rockFloor9:{
    width: 1,
    height: 3,
    x: -5,
    y: -8,
    collision: true,
  },rockFloor10:{
    width: 1,
    height: 1,
    x: -5,
    y: -7,
    collision: true,
  },rockFloor11:{
    width: 1,
    height: 1,
    x: 0,
    y: -7,
    collision: true,
  },
  rockFloor12: {
    width: 1,
    height: 2,
    x:-5,
    y: -8,
    collision: false,
  },rockFloor13: {
    width: 1,
    height: 1,
    x:-5,
    y: -10,
    collision: false,
  },rockFloor14: {
    width: 1,
    height: 1,
    x:0,
    y: -10,
    collision: false,
  },waterFloor1: {
    width: 2,
    height: 2,
    x: 9,
    y: -3,
    collision: false,
  },
  waterFloor2: {
    width: 3,
    height: 2,
    x: 7,
    y: -3.5,
    collision: false,
  },waterFloor3: {
    width: 2,
    height: 1,
    x: 9,
    y: -4.9,
    collision: false,
  },waterFloor4: {
    width: 2,
    height: 1,
    x: 9,
    y: -6,
    collision: false,
  },waterFloor5: {
    width: 1,
    height: 2,
    x: 5.9,
    y: -3.5,
    collision: false,
  },
  tree1: {
    width: 8,
    height: 2,
    x: 10,
    y: -9.8,
    collision: true,
  },
  tree2: {
    width: 2,
    height: 2,
    x: 10,
    y: -12.8,
    collision: true,
  },
  tree3: {
    width: 5,
    height: 3,
    x: 10,
    y: -15,
    collision: true,
  },
  tree4: {
    width: 5,
    height: 3,
    x: 10,
    y: -18,
    collision: true,
  },
  tree5: {
    width: 5,
    height: 3,
    x: 5,
    y: -15,
    collision: true,
  },
  tree6: {
    width: 5,
    height: 3,
    x: 5,
    y: -18,
    collision: true,
  },
  tree7: {
    width:2,
    height: 2,
    x: 8,
    y: -12.8,
    collision: true,
  },
  tree8: {
    width: 2,
    height: 2,
    x: 6,
    y: -12.8,
    collision: true,
  },
  tree9: {
    width: 2,
    height: 2,
    x: 4,
    y: -12.8,
    collision: true,
  },
  redHouse1: {
    width: 4,
    height: 3,
    x: 13,
    y: -21,
    collision: true,
  },
  redHouse2: {
    width: 4,
    height: 3,
    x: 8.5,
    y: -21,
    collision: true,
  },
  redHouse3: {
    width: 4,
    height: 4,
    x: 18.5,
    y: -25,
    collision: true,
  },
  redHouse4: {
    width: 3,
    height: 3,
    x: 9,
    y: -25,
    collision: true,
  },
  greenHouse1: {
    width: 4,
    height: 3,
    x: 13,
    y: -29,
    collision: true,
  },
  greenHouse2: {
    width: 4,
    height: 3,
    x: 8.5,
    y: -29,
    collision: true,
  },
  greenHouse3: {
    width: 4,
    height: 4,
    x: 18.5,
    y: -33,
    collision: true,
  },
  greenHouse4: {
    width: 3,
    height: 3,
    x: 9,
    y: -33,
    collision: true,
  },
  blueHouse1: {
    width: 4,
    height: 3,
    x: 13,
    y: -37,
    collision: true,
  },
  blueHouse2: {
    width: 4,
    height: 3,
    x: 8.5,
    y: -37,
    collision: true,
  },
  blueHouse3: {
    width: 4,
    height: 4,
    x: 18.5,
    y: -41,
    collision: true,
  },
  blueHouse4: {
    width: 3,
    height: 3,
    x: 9,
    y: -41,
    collision: true,
  },
  garden1: {
    width: 4,
    height: 1,
    x: 17,
    y: -12,
    collision: true,
  },
  garden2: {
    width: 1,
    height: 1,
    x: 17,
    y: -12,
    collision: true,
  },
  garden3: {
    width: 1,
    height: 1,
    x: 16,
    y: -12,
    collision: true,
  },
  garden4: {
    width: 1,
    height: 1,
    x: 15,
    y: -12,
    collision: true,
  },
  garden5: {
    width: 1,
    height: 1,
    x: 14,
    y: -12,
    collision: true,
  },
  garden6: {
    width: 1,
    height: 1,
    x: 13,
    y: -12,
    collision: true,
  },
  garden7: {
    width: 1,
    height: 1,
    x: 12,
    y: -12,
    collision: true,
  },
  garden8: {
    width: 1,
    height: 1,
    x: 13,
    y: -18,
    collision: true,
  },
  garden9: {
    width: 1,
    height: 1,
    x: 14,
    y: -18,
    collision: true,
  },
  garden10: {
    width: 1,
    height: 1,
    x: 15,
    y: -18,
    collision: true,
  },garden11: {
    width: 2,
    height: 1,
    x: 13,
    y: -19,
    collision: true,
  },garden12: {
    width: 2,
    height: 1,
    x: 15,
    y: -19,
    collision: true,
  },garden13: {
    width: 2,
    height: 1,
    x: 15,
    y: -20,
    collision: true,
  },
  billboard1:{
    width: 1,
    height: 2,
    x: 12,
    y: -13,
    collision: true,
  },
  billboard2:{
    width: 1,
    height: 1,
    x: 11,
    y: -13,
    collision: true,
  },
  billboard3:{
    width: 1,
    height: 1,
    x: 11,
    y: -14,
    collision: true,
  },
  billboard4:{
    width: 1,
    height: 1,
    x: 11,
    y: -15,
    collision: true,
  },fence1:{
    width: 1,
    height: 1,
    x: 13,
    y: -15,
    collision: true,
  },fence2:{//|
    width: 1,
    height: 1,
    x: 13,
    y: -16,
    collision: true,
  },fence3:{
    width: 1,
    height: 1,
    x: 13,
    y: -17,
    collision: true,
  },fence4:{//-
    width: 1,
    height: 1,
    x: 14,
    y: -15,
    collision: true,
  },rock1:{
    width: 2,
    height: 2,
    x: 17.1,
    y: -18.2,
    collision: true,
  },rock2:{
    width: 1,
    height: 1,
    x: 17,
    y: -15,
    collision: true,
  },rock3:{
    width: 1,
    height: 2,
    x: 15.96,
    y: -14,
    collision: true,
  },rock4:{
    width: 2,
    height: 2,
    x: 19,
    y: -13,
    collision: true,
  },flower1:{
    width: 1,
    height: 2,
    x: 17,
    y: -13,
    collision: false,
  },flower2:{
    width: 2,
    height: 3,
    x: 2,
    y: -23,
    collision: false,
  },
  mushroom1:{
    width: 2,
    height: 1,
    x: 2,
    y: -26.5,
    collision: false,
  },
  mushroom2:{
    width: 2,
    height: 1,
    x: 2,
    y: -26.5,
    collision: false,
  },
  mushroom3:{
    width: 2,
    height: 1,
    x: 2,
    y: -30.5,
    collision: false,
  },
  fruit1:{
    width: 2,
    height: 2,
    x: 4,
    y: -21,
    collision: false,
  },
  fruit2:{
    width: 2,
    height: 2,
    x: 2,
    y: -21,
    collision: false,
  },
  fruit3:{
    width: 2,
    height: 2,
    x: 4,
    y: -23,
    collision: false,
  }
};

export const map1 = {
  unit: 48,
  objects: {
    floor7: [
      { top: 0, left: 0 },
      { top: 0, left: 1 },
      { top: 0, left: 2 },
      { top: 0, left: 3 },
      { top: 0, left: 4 },
      { top: 1, left: 0 },
      { top: 1, left: 1 },
      { top: 1, left: 2 },
      { top: 1, left: 3 },
      { top: 1, left: 4 },
      { top: 1, left: 8 },
      { top: 1, left: 9 },
      { top: 1, left: 10 },
      { top: 1, left: 11 },
      { top: 1, left: 12 },
      { top: 1, left: 13 },
      { top: 1, left: 14 },
      { top: 0, left: 8 },
      { top: 0, left: 9 },
      { top: 0, left: 10 },
      { top: 0, left: 11 },
      { top: 0, left: 12 },
      { top: 0, left: 13 },
      { top: 0, left: 14 },
      { top: 2, left: 0 },
      { top: 2, left: 1 },
      { top: 2, left: 2 },
      { top: 2, left: 3 },
      { top: 2, left: 4 },
      { top: 2, left: 8 },
      { top: 2, left: 9 },
      { top: 2, left: 10 },
      { top: 2, left: 11 },
      { top: 2, left: 12 },
      { top: 2, left: 13 },
      { top: 2, left: 14 },
      { top: 3, left: 0 },
      { top: 3, left: 1 },
      { top: 3, left: 2 },
      { top: 3, left: 3 },
      { top: 3, left: 4 },
      { top: 3, left: 8 },
      { top: 3, left: 9 },
      { top: 3, left: 10 },
      { top: 3, left: 11 },
      { top: 3, left: 12 },
      { top: 3, left: 13 },
      { top: 3, left: 14 },
      { top: 4, left: 0 },
      { top: 4, left: 1 },
      { top: 4, left: 2 },
      { top: 4, left: 3 },
      { top: 4, left: 4 },
      { top: 4, left: 8 },
      { top: 4, left: 9 },
      { top: 4, left: 13 },
      { top: 4, left: 14 },
      { top: 5, left: 8 },
      { top: 5, left: 9 },
      { top: 5, left: 13 },
      { top: 5, left: 14 },
      { top: 6, left: 13 },
      { top: 6, left: 14 },
      { top: 7, left: 0 },
      { top: 7, left: 1 },
      { top: 7, left: 2 },
      { top: 7, left: 3 },
      { top: 7, left: 4 },
      { top: 7, left: 5 },
      { top: 7, left: 6 },
      { top: 7, left: 7 },
      { top: 7, left: 10 },
      { top: 7, left: 11 },
      { top: 7, left: 12 },
      { top: 7, left: 13 },
      { top: 7, left: 14 },
      { top: 8, left: 0 },
      { top: 8, left: 1 },
      { top: 8, left: 2 },
      { top: 8, left: 3 },
      { top: 8, left: 4 },
      { top: 8, left: 5 },
      { top: 8, left: 6 },
      { top: 8, left: 7 },
      { top: 8, left: 10 },
      { top: 8, left: 11 },
      { top: 8, left: 12 },
      { top: 8, left: 13 },
      { top: 8, left: 14 },
      { top: 9, left: 0 },
      { top: 9, left: 1 },
      { top: 9, left: 2 },
      { top: 9, left: 3 },
      { top: 9, left: 4 },
      { top: 9, left: 5 },
      { top: 9, left: 6 },
      { top: 9, left: 7 },
      { top: 9, left: 10 },
      { top: 9, left: 11 },
      { top: 9, left: 12 },
      { top: 9, left: 13 },
      { top: 9, left: 14 },
    ],
    tree3: [{ top: 0, left: 0 }],
    floor1: [
      { top: 0, left: 6 },
      { top: 1, left: 6 },
      { top: 2, left: 6 },
      { top: 3, left: 6 },
      { top: 4, left: 6 },
      { top: 5, left: 6 },
    ],
    floor3: [
      { top: 0, left: 5 },
      { top: 1, left: 5 },
      { top: 2, left: 5 },
      { top: 3, left: 5 },
      { top: 4, left: 5 },
      { top: 7, left: 8 },
      { top: 8, left: 8 },
      { top: 9, left: 8 },
    ],
    tree4: [{ top: 2, left: 0 }],
    floor4: [{ top: 5, left: 5 }],
    floor5: [
      { top: 5, left: 0 },
      { top: 6, left: 8 },
    ],
    floor6: [
      { top: 6, left: 0 },
      { top: 6, left: 2 },
      { top: 6, left: 4 },
    ],
    floor8: [
      { top: 5, left: 1 },
      { top: 5, left: 3 },
    ],
    floor9: [
      { top: 4, left: 7 },
      { top: 6, left: 7 },
    ],
    floor11: [
      { top: 5, left: 7 },
      { top: 9, left: 9 },
      { top: 6, left: 9 },
      { top: 7, left: 9 },
      { top: 8, left: 9 },
      { top: 4, left: 7 },
      { top: 3, left: 7 },
      { top: 2, left: 7 },
      { top: 1, left: 7 },
      { top: 0, left: 7 },
    ],
    floor12: [{ top: 6, left: 9 }],
    house1: [
      { top: 7, left: 0 },
      { top: 7, left: 4 },
    ],
    waterpool: [{ top: 4, left: 10 }],
    floor2: [{ top: 6, left: 6 }],
    tree2: [
      { top: 0, left: 9 },
      { top: 0, left: 12 },
    ],
  },
};

export const map1Collision = [
  '0,0',
  '0,1',
  '0,2',
  '1,0',
  '1,1',
  '1,2',
  '2,0',
  '2,1',
  '2,2',
  '3,0',
  '3,1',
  '3,2',
  '4,0',
  '4,1',
  '4,2',
  '0,3',
  '0,4',
  '1,3',
  '1,4',
  '2,3',
  '2,4',
  '3,3',
  '3,4',
  '4,3',
  '4,4',
  '0,7',
  '0,8',
  '0,9',
  '1,7',
  '1,8',
  '1,9',
  '2,7',
  '2,8',
  '2,9',
  '3,7',
  '3,8',
  '3,9',
  '4,7',
  '4,8',
  '4,9',
  '5,7',
  '5,8',
  '5,9',
  '6,7',
  '6,8',
  '6,9',
  '7,7',
  '7,8',
  '7,9',
  '10,4',
  '10,5',
  '10,6',
  '11,4',
  '11,5',
  '11,6',
  '12,4',
  '12,5',
  '12,6',
  '9,0',
  '9,1',
  '10,0',
  '10,1',
  '12,0',
  '12,1',
  '13,0',
  '13,1',
];
export const wrapperWidth = '920';
export const wrapperHeight = '680';
export const mapBorder = '100';
export const mapWidth = (wrapperWidth - 2 * mapBorder) / map1.unit;
export const mapHeight = (wrapperHeight - 2 * mapBorder) / map1.unit;
export const playerWidth = '60';
export const playerHeight = '60';
export const startingPoint = {top:230, left:330, direction:"down", frame:0}
